name: 'on-pr-master-format-lint'
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint-format:
    name: lint-and-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: build
        run: npm install
      - name: format
        run: npm run format
      - name: lint
        run: npm run lint
      - run: npm test
