name: 'pr-linter-formatter'
on:
  pull_request:
  push:
    branches:
      - test-git-action
jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: build
        run: npm install
      - name: formatter
        run: npm run formatter
      - name: lint
        run: npm run lint
      - run: npm test
